Update dgl APIs for v1.1.0 (#3546)
DGL v1.1.0 introduced a breaking change that renames `adj_sparse` to `adj_tensors`, causing the following error in our CI:
```
nn/test_gatconv.py::test_gatconv_equality[False-None-1-False] - AttributeError: 'DGLGraph' object has no attribute 'adj_sparse'
nn/test_gatconv.py::test_gatconv_equality[False-None-1-True] - AttributeError: 'DGLBlock' object has no attribute 'adj_sparse'
```

 This PR updates the usage in `cugraph-dgl` tests.

CC: @alexbarghi-nv

Authors:
  - Tingyu Wang (https://github.com/tingyu66)

Approvers:
  - Alex Barghi (https://github.com/alexbarghi-nv)
  - AJ Schmidt (https://github.com/ajschmidt8)

URL: https://github.com/rapidsai/cugraph/pull/3546